import { Engine } from '@point0/engine'
export const engine = Engine.create({
  file: import.meta.url,
  pointsGlob: ['**/*.{ts,tsx}'],
  serveRetries: 99,
  ssr: true,
  server: {
    scope: 'root',
    entry: { main: './index.server.ts' },
    points: async () => await import('./lib/points.server.js'),
    generate: { points: './lib/points.server.ts' },
    outdir: '../dist/server',
    env: { vars: { MY_ENV_SERVER_VARIABLE: 'SERVER1' }, consts: ['MY_ENV_FILE_CONSTANT'] },
    // publicdir: server,
    // port: server,
    // hmrPort: server,
    // viteConfig: '../vite.config.ts',
  },
  clients: [
    {
      scope: 'root',
      app: async () => await import('./app.js'),
      points: async () => await import('./lib/points.client.js'),
      routes: async () => await import('./lib/routes.js'),
      generate: { points: './lib/points.client.ts', routes: './lib/routes.ts' },
      indexHtml: './index.html',
      outdir: '../dist/client',
      publicdir: { source: '../public', outdir: '../dist/client' },
      env: { vars: ['MY_ENV_FILE_VARIABLE'], consts: ['MY_ENV_FILE_CONSTANT'] },
      // serving: client,
      // port: client,
      // hmrPort: client,
      // viteConfig: '../vite.config.ts',
    },
  ],
})
