import { describe, it, expect } from 'bun:test'
import { parseEngineOptions } from '../src/config.js'
import { omit } from 'lodash'
import { Point0 } from '@point0/core'

describe('parseEngineOptions', () => {
  it('should parse engine options', () => {
    const POINT0_ENGINE_WAS_BUILT = false as boolean
    const options = parseEngineOptions({
      itWasBuilt: POINT0_ENGINE_WAS_BUILT,
      cwdAfterBuild: !POINT0_ENGINE_WAS_BUILT ? '../dist/server' : '/home/dist/server',
      cwdBeforeBuild: !POINT0_ENGINE_WAS_BUILT ? '/home/src' : '../src',
      // below all paths should be relative to cwdBeforeBuild like it was not built yet
      server: {
        scope: 'server',
        points: { _root_ready: Point0.create('server').root() } as never,
        port: 3000,
        entry: './index.server.ts',
        outdir: '../dist/server',
        publicdirOutdir: '../dist/public',
      },
      clients: [
        {
          scope: 'client',
          points: { _root_ready: Point0.create('client').root() } as never,
          generatePointsReady: './lib/points.ready.js',
          indexHtml: './index.html',
          port: 3001,
          env: ['SOURCE_BASE_URL'],
          publicdir: './public',
          outdir: '../dist/client',
          publicdirOutdir: '../dist/client',
        },
      ],
    })
    expect(omit(options, ['server.points'])).toMatchInlineSnapshot(`
      {
        "clients": [
          {
            "app": null,
            "banner": null,
            "baseurl": "/",
            "bunBuildConfig": {},
            "bunPlugins": [],
            "domRootElementId": "root",
            "engineFile": null,
            "env": {
              "SOURCE_BASE_URL": undefined,
            },
            "hmrPort": 3101,
            "index": 0,
            "indexHtml": "/home/src/index.html",
            "outdir": "/home/dist/client",
            "points": PointsManager {
              "Infer": {},
              "_getPagePointByHref": [Function],
              "absPath": null,
              "basepath": null,
              "baseurl": undefined,
              "collection": [],
              "hostname": null,
              "isPageLocationSuitable": [Function],
              "loadSuitablePage": [Function: AsyncFunction],
              "pagesTree": [],
              "pagesTreeSource": [],
              "prefetchSuitablePagePoint": [Function: AsyncFunction],
              "readFn": null,
              "ready": true,
              "root": Point0 {
                "Infer": "__I_AM_POINT0__",
                "Provider": [Function],
                "_Component": [Function],
                "_Layout": [Function],
                "_Page": [Function],
                "_ProviderReactContext": undefined,
                "_attachedTo": [],
                "_base": Point0 {
                  "Infer": "__I_AM_POINT0__",
                  "Provider": [Function],
                  "_Component": [Function],
                  "_Layout": [Function],
                  "_Page": [Function],
                  "_ProviderReactContext": undefined,
                  "_attachedTo": [],
                  "_base": undefined,
                  "_baseurl": undefined,
                  "_clientExecuteActions": [],
                  "_component": undefined,
                  "_componentErrorComponent": [Function],
                  "_componentLoadingComponent": [Function],
                  "_defaultComponentQueryOptions": {},
                  "_defaultInfiniteQueryOptions": {},
                  "_defaultLayoutQueryOptions": {},
                  "_defaultMutationOptions": {},
                  "_defaultPageQueryOptions": {},
                  "_defaultProviderQueryOptions": {},
                  "_defaultQueryOptions": {},
                  "_errorComponent": undefined,
                  "_fetchOptions": [Function],
                  "_headFns": [],
                  "_infiniteQueryOptions": {},
                  "_layout": undefined,
                  "_layoutErrorComponent": [Function],
                  "_layoutLoadingComponent": [Function],
                  "_layouts": [],
                  "_letsEndPointType": "root",
                  "_loadingComponent": undefined,
                  "_mutationOptions": {},
                  "_onPrefetchFns": [],
                  "_page": undefined,
                  "_pageErrorComponent": [Function],
                  "_pageLoadingComponent": [Function],
                  "_prefetchPolicy": "everything",
                  "_prevRoute": undefined,
                  "_providerValueSetter": undefined,
                  "_queryOptions": {},
                  "_queryResultType": undefined,
                  "_root": undefined,
                  "_route": undefined,
                  "_scrollPositionGetter": [Function],
                  "_scrollPositionRestorePolicy": [Function],
                  "_scrollPositionSetter": [Function],
                  "_serverExecuteActions": [],
                  "_serverInputSchema": undefined,
                  "_serverurl": undefined,
                  "_ssr": false,
                  "_tranformer": {
                    "deserialize": [Function: deserialize],
                    "parse": [Function],
                    "serialize": [Function: serialize],
                    "stringify": [Function],
                  },
                  "_unstableId": 70,
                  "_useValue": undefined,
                  "_wrappers": [],
                  "inputSchema": undefined,
                  "name": "client",
                  "point": [Circular],
                  "scope": "client",
                  "shouldBePrefetchedOnLinkHover": false,
                  "type": "middleware",
                  "useMutation": [Function],
                },
                "_baseurl": undefined,
                "_clientExecuteActions": [],
                "_component": undefined,
                "_componentErrorComponent": [Function],
                "_componentLoadingComponent": [Function],
                "_defaultComponentQueryOptions": {},
                "_defaultInfiniteQueryOptions": {},
                "_defaultLayoutQueryOptions": {},
                "_defaultMutationOptions": {},
                "_defaultPageQueryOptions": {},
                "_defaultProviderQueryOptions": {},
                "_defaultQueryOptions": {},
                "_errorComponent": undefined,
                "_fetchOptions": [Function],
                "_headFns": [],
                "_infiniteQueryOptions": {},
                "_layout": undefined,
                "_layoutErrorComponent": [Function],
                "_layoutLoadingComponent": [Function],
                "_layouts": [],
                "_letsEndPointType": "root",
                "_loadingComponent": undefined,
                "_mutationOptions": {},
                "_onPrefetchFns": [],
                "_page": undefined,
                "_pageErrorComponent": [Function],
                "_pageLoadingComponent": [Function],
                "_prefetchPolicy": "everything",
                "_prevRoute": undefined,
                "_providerValueSetter": undefined,
                "_queryOptions": {},
                "_queryResultType": undefined,
                "_root": Point0 {
                  "Infer": "__I_AM_POINT0__",
                  "Provider": [Function],
                  "_Component": [Function],
                  "_Layout": [Function],
                  "_Page": [Function],
                  "_ProviderReactContext": undefined,
                  "_attachedTo": [],
                  "_base": undefined,
                  "_baseurl": undefined,
                  "_clientExecuteActions": [],
                  "_component": undefined,
                  "_componentErrorComponent": [Function],
                  "_componentLoadingComponent": [Function],
                  "_defaultComponentQueryOptions": {},
                  "_defaultInfiniteQueryOptions": {},
                  "_defaultLayoutQueryOptions": {},
                  "_defaultMutationOptions": {},
                  "_defaultPageQueryOptions": {},
                  "_defaultProviderQueryOptions": {},
                  "_defaultQueryOptions": {},
                  "_errorComponent": undefined,
                  "_fetchOptions": [Function],
                  "_headFns": [],
                  "_infiniteQueryOptions": {},
                  "_layout": undefined,
                  "_layoutErrorComponent": [Function],
                  "_layoutLoadingComponent": [Function],
                  "_layouts": [],
                  "_letsEndPointType": "root",
                  "_loadingComponent": undefined,
                  "_mutationOptions": {},
                  "_onPrefetchFns": [],
                  "_page": undefined,
                  "_pageErrorComponent": [Function],
                  "_pageLoadingComponent": [Function],
                  "_prefetchPolicy": "everything",
                  "_prevRoute": undefined,
                  "_providerValueSetter": undefined,
                  "_queryOptions": {},
                  "_queryResultType": undefined,
                  "_root": undefined,
                  "_route": undefined,
                  "_scrollPositionGetter": [Function],
                  "_scrollPositionRestorePolicy": [Function],
                  "_scrollPositionSetter": [Function],
                  "_serverExecuteActions": [],
                  "_serverInputSchema": undefined,
                  "_serverurl": undefined,
                  "_ssr": false,
                  "_tranformer": {
                    "deserialize": [Function: deserialize],
                    "parse": [Function],
                    "serialize": [Function: serialize],
                    "stringify": [Function],
                  },
                  "_unstableId": 70,
                  "_useValue": undefined,
                  "_wrappers": [],
                  "inputSchema": undefined,
                  "name": "client",
                  "point": [Circular],
                  "scope": "client",
                  "shouldBePrefetchedOnLinkHover": false,
                  "type": "middleware",
                  "useMutation": [Function],
                },
                "_route": undefined,
                "_scrollPositionGetter": [Function],
                "_scrollPositionRestorePolicy": [Function],
                "_scrollPositionSetter": [Function],
                "_serverExecuteActions": [],
                "_serverInputSchema": undefined,
                "_serverurl": undefined,
                "_ssr": false,
                "_tranformer": {
                  "deserialize": [Function: deserialize],
                  "parse": [Function],
                  "serialize": [Function: serialize],
                  "stringify": [Function],
                },
                "_unstableId": 71,
                "_useValue": undefined,
                "_wrappers": [],
                "inputSchema": undefined,
                "name": "client",
                "point": [Circular],
                "scope": "client",
                "shouldBePrefetchedOnLinkHover": false,
                "type": "root",
                "useMutation": [Function],
              },
              "routes": Routes Routes {
                "_": {
                  "getLocation": [Function: _getLocation],
                  "keysOrdering": [],
                  "ordered": [],
                  "override": [Function: _override],
                  "pathsOrdering": [],
                  "routes": {},
                },
                "_keysOrdering": [],
                "_ordered": [],
                "_pathsOrdering": [],
                "_routes": {},
                "override": [Function: _override],
              },
              "routesHash": "",
              "scope": "client",
              "ssr": false,
              "transformer": {
                "deserialize": [Function: deserialize],
                "parse": [Function],
                "serialize": [Function: serialize],
                "stringify": [Function],
              },
            },
            "pointsLazy": null,
            "pointsReady": "./lib/points.ready.js",
            "port": 3001,
            "prune": true,
            "publicdir": [
              [
                "/",
                "/home/src/public",
              ],
            ],
            "publicdirOutdir": "/home/dist/client",
            "routes": null,
            "scope": "client",
            "viteConfig": null,
          },
        ],
        "general": {
          "autoFixBuiltPaths": true,
          "banner": null,
          "buildWatchGlob": [],
          "clientsOutdir": null,
          "cwd": "/home/src",
          "cwdAfterBuild": "/home/dist/server",
          "cwdBeforeBuild": "/home/src",
          "engineFile": null,
          "fallbackScope": "client",
          "itWasBuilt": false,
          "logger": {
            "error": [Function: error],
            "info": [Function: info],
          },
          "pointsGlob": [],
        },
        "server": {
          "banner": null,
          "bunBuildConfig": {},
          "bunPlugins": [],
          "cwdBeforeBuild": "/home/src",
          "engineFile": null,
          "entry": {
            "main": "/home/src/index.server.ts",
          },
          "fallbackScope": "client",
          "hmrPort": 3100,
          "itWasBuilt": false,
          "outdir": "/home/dist/server",
          "pointsLazy": null,
          "pointsReady": null,
          "port": 3000,
          "publicdir": [],
          "publicdirOutdir": "/home/dist/public",
          "routes": null,
          "scope": "server",
          "viteConfig": null,
        },
      }
    `)
  })

  it('should parse engine options when it was built', () => {
    const POINT0_ENGINE_WAS_BUILT = true as boolean
    const options = parseEngineOptions({
      itWasBuilt: POINT0_ENGINE_WAS_BUILT,
      cwdAfterBuild: !POINT0_ENGINE_WAS_BUILT ? '../dist/server' : '/home/dist/server',
      cwdBeforeBuild: !POINT0_ENGINE_WAS_BUILT ? '/home/src' : '../../src',
      // below all paths should be relative to cwdBeforeBuild like it was not built yet
      server: {
        scope: 'server',
        points: { _root_ready: Point0.create('server').root() } as never,
        port: 3000,
        entry: './index.server.ts',
        outdir: '../dist/server',
        publicdirOutdir: '../dist/public',
      },
      clients: [
        {
          scope: 'client',
          points: { _root_ready: Point0.create('client').root() } as never,
          generatePointsReady: './lib/points.ready.js',
          indexHtml: './index.html',
          port: 3001,
          env: ['SOURCE_BASE_URL'],
          publicdir: './public',
          outdir: '../dist/client',
          publicdirOutdir: '../dist/client',
        },
      ],
    })
    expect(omit(options, ['server.points', 'clients.0.points'])).toMatchInlineSnapshot(`
      {
        "clients": [
          {
            "app": null,
            "banner": null,
            "baseurl": "/",
            "bunBuildConfig": {},
            "bunPlugins": [],
            "domRootElementId": "root",
            "engineFile": null,
            "env": {
              "SOURCE_BASE_URL": undefined,
            },
            "hmrPort": 3101,
            "index": 0,
            "indexHtml": "/home/dist/client/index.html",
            "outdir": "/home/dist/client",
            "pointsLazy": null,
            "pointsReady": "./lib/points.ready.js",
            "port": 3001,
            "prune": true,
            "publicdir": [
              [
                "/",
                "/home/dist/client",
              ],
            ],
            "publicdirOutdir": "/home/dist/client",
            "routes": null,
            "scope": "client",
            "viteConfig": null,
          },
        ],
        "general": {
          "autoFixBuiltPaths": true,
          "banner": null,
          "buildWatchGlob": [],
          "clientsOutdir": null,
          "cwd": "/home/dist/server",
          "cwdAfterBuild": "/home/dist/server",
          "cwdBeforeBuild": "/home/src",
          "engineFile": null,
          "fallbackScope": "client",
          "itWasBuilt": true,
          "logger": {
            "error": [Function: error],
            "info": [Function: info],
          },
          "pointsGlob": [],
        },
        "server": {
          "banner": null,
          "bunBuildConfig": {},
          "bunPlugins": [],
          "cwdBeforeBuild": "/home/src",
          "engineFile": null,
          "entry": {
            "main": "/home/dist/server/index.server.js",
          },
          "fallbackScope": "client",
          "hmrPort": 3100,
          "itWasBuilt": true,
          "outdir": "/home/dist/server",
          "pointsLazy": null,
          "pointsReady": null,
          "port": 3000,
          "publicdir": [],
          "publicdirOutdir": "/home/dist/public",
          "routes": null,
          "scope": "server",
          "viteConfig": null,
        },
      }
    `)
  })
})
