import { defineConfig } from 'tsdown'

export default defineConfig({
  entry: [
    'src/schema/arktype.ts',
    'src/schema/typebox.ts',
    'src/schema/valibot.ts',
    'src/schema/yup.ts',
    'src/schema/zod.ts',
    'src/schema/superstruct.ts',
    'src/schema/utils.ts',
    'src/client-only.ts',
    'src/client-points.ts',
    'src/cookie-store.ts',
    'src/effects.ts',
    'src/env.ts',
    'src/error.ts',
    'src/env.types.ts',
    'src/eventer.ts',
    'src/helpers.ts',
    'src/index.ts',
    'src/internals.ts',
    'src/logger.ts',
    'src/mountable.ts',
    'src/point0.ts',
    'src/points-manager.ts',
    'src/query-client.ts',
    'src/redirect.ts',
    'src/request0.ts',
    'src/server-only.ts',
    'src/navigation.tsx',
    'src/ssr-store.ts',
    'src/super-store.ts',
    'src/types.ts',
    'src/unhead.ts',
    'src/utils.ts',
    'src/virtual.ts',
  ],
  format: 'esm',
  platform: 'node',
  target: 'es2022',
  outDir: 'dist',
  clean: true,
  dts: { resolver: 'tsc' },
  sourcemap: false,
  unbundle: true,
  treeshake: true,
  outExtensions: () => ({ js: '.js' }),
  tsconfig: './tsconfig.build.json',
  deps: {
    skipNodeModulesBundle: true,
    neverBundle: ['bun', /^@types\//, /^@point0\//],
  },
})
