import { fixImportsPlugin } from 'esbuild-fix-imports-plugin'
import { defineConfig, type Options } from 'tsup'

const general = {
  entry: [
    'src/schema/arktype.ts',
    'src/schema/typebox.ts',
    'src/schema/valibot.ts',
    'src/schema/yup.ts',
    'src/schema/zod.ts',
    'src/schema/superstruct.ts',
    'src/schema/utils.ts',
    'src/client-points.ts',
    'src/effects.ts',
    'src/env.ts',
    'src/error.ts',
    'src/env.types.ts',
    'src/eventer.ts',
    'src/helpers.ts',
    'src/index.ts',
    'src/internals.ts',
    'src/logger.ts',
    'src/mountable.ts',
    'src/point0.ts',
    'src/points-manager.ts',
    'src/query-client.ts',
    'src/request0.ts',
    'src/navigation.tsx',
    'src/super-store.ts',
    'src/types.ts',
    'src/unhead.ts',
    'src/utils.ts',
  ],
  clean: false,
  dts: true,
  sourcemap: false,
  splitting: false,
  minify: false,
  target: 'es2022',
  external: ['bun:test'],
  treeshake: true,
  bundle: false,
  outExtension: ({ format }) => ({ js: format === 'cjs' ? '.cjs' : '.js' }),
  esbuildPlugins: [fixImportsPlugin()],
  platform: 'node',
  tsconfig: './tsconfig.build.json',
} satisfies Options

export default defineConfig([
  {
    ...general,
    format: 'esm',
    outDir: 'dist/esm',
  },
  {
    ...general,
    format: 'cjs',
    outDir: 'dist/cjs',
  },
])
