import { Route0 } from '@devp0nt/route0'
import { Engine } from '@point0/engine'
export default {
  engine: {
    file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/engine.ts',
    import: async () => (await Engine.findAndImportSelf({ engineFile: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/engine.ts' })).engine,
    server: {
      scope: 'client',
    },
    clients: [
      {
        scope: 'client',
      },
    ],
  },
  points: [
    {
      scope: 'client',
      type: 'root',
      name: 'client',
      id: 'client.root.client',
      route: undefined,
      endpoint: undefined,
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
        line: 5,
        column: 22,
      },
      import: async () => (await import('./client.js')).client,
      valid: true,
      errors: [],
      ssr: true,
      parents: [],
      layouts: [],
    },
    {
      scope: 'client',
      type: 'page',
      name: 'home',
      id: 'client.page.home',
      route: Route0.create('/'),
      endpoint: {
        method: 'GET',
        route: Route0.create('/_point0/client/page/home'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/home.tsx',
        line: 102,
        column: 15,
      },
      import: async () => (await import('../pages/home.js')).default,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'client',
          type: 'layout',
          name: 'generalLayout',
          id: 'client.layout.generalLayout',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/general.tsx',
            line: 7,
            column: 29,
          },
        },
        {
          scope: 'client',
          type: 'root',
          name: 'client',
          id: 'client.root.client',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 22,
          },
        },
      ],
      layouts: [
        {
          scope: 'client',
          type: 'layout',
          name: 'generalLayout',
          id: 'client.layout.generalLayout',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/general.tsx',
            line: 7,
            column: 29,
          },
        },
      ],
    },
    {
      scope: 'client',
      type: 'page',
      name: 'empty',
      id: 'client.page.empty',
      route: Route0.create('/empty/:x'),
      endpoint: {
        method: 'GET',
        route: Route0.create('/_point0/client/page/empty/empty/:x'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/empty.tsx',
        line: 20,
        column: 21,
      },
      import: async () => (await import('../pages/empty.js')).empty,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'client',
          type: 'root',
          name: 'client',
          id: 'client.root.client',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 22,
          },
        },
      ],
      layouts: [],
    },
    {
      scope: 'client',
      type: 'page',
      name: 'file',
      id: 'client.page.file',
      route: Route0.create('/file'),
      endpoint: {
        method: 'GET',
        route: Route0.create('/_point0/client/page/file/file'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/file.tsx',
        line: 6,
        column: 24,
      },
      import: async () => (await import('../pages/file.js')).filePage,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'client',
          type: 'root',
          name: 'client',
          id: 'client.root.client',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 22,
          },
        },
      ],
      layouts: [],
    },
    {
      scope: 'client',
      type: 'page',
      name: 'gi1',
      id: 'client.page.gi1',
      route: Route0.create('/gi1'),
      endpoint: {
        method: 'GET',
        route: Route0.create('/_point0/client/page/gi1/gi1'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/x/gi2.tsx',
        line: 27,
        column: 23,
      },
      import: async () => (await import('../pages/x/gi2.js')).gi1Page,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'client',
          type: 'layout',
          name: 'generalLayout',
          id: 'client.layout.generalLayout',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/general.tsx',
            line: 7,
            column: 29,
          },
        },
        {
          scope: 'client',
          type: 'root',
          name: 'client',
          id: 'client.root.client',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 22,
          },
        },
      ],
      layouts: [
        {
          scope: 'client',
          type: 'layout',
          name: 'generalLayout',
          id: 'client.layout.generalLayout',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/general.tsx',
            line: 7,
            column: 29,
          },
        },
      ],
    },
    {
      scope: 'client',
      type: 'page',
      name: 'gi2',
      id: 'client.page.gi2',
      route: Route0.create('/gi2'),
      endpoint: {
        method: 'GET',
        route: Route0.create('/_point0/client/page/gi2/gi2'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/x/gi2 copy.tsx',
        line: 27,
        column: 23,
      },
      import: async () => (await import('../pages/x/gi2 copy.js')).gi1Page,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'client',
          type: 'layout',
          name: 'generalLayout',
          id: 'client.layout.generalLayout',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/general.tsx',
            line: 7,
            column: 29,
          },
        },
        {
          scope: 'client',
          type: 'root',
          name: 'client',
          id: 'client.root.client',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 22,
          },
        },
      ],
      layouts: [
        {
          scope: 'client',
          type: 'layout',
          name: 'generalLayout',
          id: 'client.layout.generalLayout',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/general.tsx',
            line: 7,
            column: 29,
          },
        },
      ],
    },
    {
      scope: 'client',
      type: 'page',
      name: 'ideas',
      id: 'client.page.ideas',
      route: Route0.create('/ideas'),
      endpoint: {
        method: 'GET',
        route: Route0.create('/_point0/client/page/ideas/ideas'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/ideas.tsx',
        line: 6,
        column: 25,
      },
      import: async () => (await import('../pages/ideas.js')).ideasPage,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'client',
          type: 'layout',
          name: 'generalLayout',
          id: 'client.layout.generalLayout',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/general.tsx',
            line: 7,
            column: 29,
          },
        },
        {
          scope: 'client',
          type: 'root',
          name: 'client',
          id: 'client.root.client',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 22,
          },
        },
      ],
      layouts: [
        {
          scope: 'client',
          type: 'layout',
          name: 'generalLayout',
          id: 'client.layout.generalLayout',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/general.tsx',
            line: 7,
            column: 29,
          },
        },
      ],
    },
    {
      scope: 'client',
      type: 'page',
      name: 'newIdea',
      id: 'client.page.newIdea',
      route: Route0.create('/ideas/new'),
      endpoint: {
        method: 'GET',
        route: Route0.create('/_point0/client/page/newIdea/ideas/new'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/idea-create.tsx',
        line: 154,
        column: 30,
      },
      import: async () => (await import('../pages/idea-create.js')).ideaCreatePage,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'client',
          type: 'layout',
          name: 'generalLayout',
          id: 'client.layout.generalLayout',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/general.tsx',
            line: 7,
            column: 29,
          },
        },
        {
          scope: 'client',
          type: 'root',
          name: 'client',
          id: 'client.root.client',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 22,
          },
        },
      ],
      layouts: [
        {
          scope: 'client',
          type: 'layout',
          name: 'generalLayout',
          id: 'client.layout.generalLayout',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/general.tsx',
            line: 7,
            column: 29,
          },
        },
      ],
    },
    {
      scope: 'client',
      type: 'page',
      name: 'idea',
      id: 'client.page.idea',
      route: Route0.create('/ideas/:id'),
      endpoint: {
        method: 'GET',
        route: Route0.create('/_point0/client/page/idea/ideas/:id'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/idea.tsx',
        line: 15,
        column: 24,
      },
      import: async () => (await import('../pages/idea.js')).ideaPage,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'client',
          type: 'layout',
          name: 'idea',
          id: 'client.layout.idea',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/idea.tsx',
            line: 5,
            column: 26,
          },
        },
        {
          scope: 'client',
          type: 'layout',
          name: 'generalLayout',
          id: 'client.layout.generalLayout',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/general.tsx',
            line: 7,
            column: 29,
          },
        },
        {
          scope: 'client',
          type: 'root',
          name: 'client',
          id: 'client.root.client',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 22,
          },
        },
      ],
      layouts: [
        {
          scope: 'client',
          type: 'layout',
          name: 'generalLayout',
          id: 'client.layout.generalLayout',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/general.tsx',
            line: 7,
            column: 29,
          },
        },
        {
          scope: 'client',
          type: 'layout',
          name: 'idea',
          id: 'client.layout.idea',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/idea.tsx',
            line: 5,
            column: 26,
          },
        },
      ],
    },
    {
      scope: 'client',
      type: 'page',
      name: 'ideaNews',
      id: 'client.page.ideaNews',
      route: Route0.create('/ideas/:id/news'),
      endpoint: {
        method: 'GET',
        route: Route0.create('/_point0/client/page/ideaNews/ideas/:id/news'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/idea-news.tsx',
        line: 5,
        column: 28,
      },
      import: async () => (await import('../pages/idea-news.js')).ideaNewsPage,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'client',
          type: 'layout',
          name: 'idea',
          id: 'client.layout.idea',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/idea.tsx',
            line: 5,
            column: 26,
          },
        },
        {
          scope: 'client',
          type: 'layout',
          name: 'generalLayout',
          id: 'client.layout.generalLayout',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/general.tsx',
            line: 7,
            column: 29,
          },
        },
        {
          scope: 'client',
          type: 'root',
          name: 'client',
          id: 'client.root.client',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 22,
          },
        },
      ],
      layouts: [
        {
          scope: 'client',
          type: 'layout',
          name: 'generalLayout',
          id: 'client.layout.generalLayout',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/general.tsx',
            line: 7,
            column: 29,
          },
        },
        {
          scope: 'client',
          type: 'layout',
          name: 'idea',
          id: 'client.layout.idea',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/idea.tsx',
            line: 5,
            column: 26,
          },
        },
      ],
    },
    {
      scope: 'client',
      type: 'page',
      name: 'md2',
      id: 'client.page.md2',
      route: Route0.create('/md2'),
      endpoint: {
        method: 'GET',
        route: Route0.create('/_point0/client/page/md2/md2'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/md2.mdx',
        line: 5,
        column: 20,
      },
      import: async () => (await import('../pages/md2.mdx')).page,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'client',
          type: 'root',
          name: 'client',
          id: 'client.root.client',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 22,
          },
        },
      ],
      layouts: [],
    },
    {
      scope: 'client',
      type: 'page',
      name: 'sharedEmpty',
      id: 'client.page.sharedEmpty',
      route: Route0.create('/sharedEmpty2'),
      endpoint: {
        method: 'GET',
        route: Route0.create('/_point0/client/page/sharedEmpty/sharedEmpty2'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/empty.tsx',
        line: 55,
        column: 31,
      },
      import: async () => (await import('../pages/empty.js')).sharedEmptyPage,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'client',
          type: 'root',
          name: 'client',
          id: 'client.root.client',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 22,
          },
        },
      ],
      layouts: [],
    },
    {
      scope: 'client',
      type: 'layout',
      name: 'generalLayout',
      id: 'client.layout.generalLayout',
      route: Route0.create('/'),
      endpoint: undefined,
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/general.tsx',
        line: 7,
        column: 29,
      },
      import: async () => (await import('../layouts/general.js')).generalLayout,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'client',
          type: 'root',
          name: 'client',
          id: 'client.root.client',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 22,
          },
        },
      ],
      layouts: [],
    },
    {
      scope: 'client',
      type: 'layout',
      name: 'idea',
      id: 'client.layout.idea',
      route: Route0.create('/ideas/:id'),
      endpoint: {
        method: 'GET',
        route: Route0.create('/_point0/client/layout/idea/ideas/:id'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/idea.tsx',
        line: 5,
        column: 26,
      },
      import: async () => (await import('../layouts/idea.js')).ideaLayout,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'client',
          type: 'layout',
          name: 'generalLayout',
          id: 'client.layout.generalLayout',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/general.tsx',
            line: 7,
            column: 29,
          },
        },
        {
          scope: 'client',
          type: 'root',
          name: 'client',
          id: 'client.root.client',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 22,
          },
        },
      ],
      layouts: [
        {
          scope: 'client',
          type: 'layout',
          name: 'generalLayout',
          id: 'client.layout.generalLayout',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/general.tsx',
            line: 7,
            column: 29,
          },
        },
      ],
    },
    {
      scope: 'client',
      type: 'component',
      name: 'bestIdea',
      id: 'client.component.bestIdea',
      route: undefined,
      endpoint: {
        method: 'POST',
        route: Route0.create('/_point0/client/component/bestIdea'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/home.tsx',
        line: 33,
        column: 33,
      },
      import: async () => (await import('../pages/home.js')).BestIdeaComponent,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'client',
          type: 'root',
          name: 'client',
          id: 'client.root.client',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 22,
          },
        },
      ],
      layouts: [],
    },
    {
      scope: 'client',
      type: 'component',
      name: 'externalHelper2',
      id: 'client.component.externalHelper2',
      route: undefined,
      endpoint: undefined,
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/home.helper.tsx',
        line: 30,
        column: 40,
      },
      import: async () => (await import('../pages/home.helper.js')).ExternalHelperComponent2,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'client',
          type: 'root',
          name: 'client',
          id: 'client.root.client',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 22,
          },
        },
      ],
      layouts: [],
    },
    {
      scope: 'client',
      type: 'component',
      name: 'externalHelper3',
      id: 'client.component.externalHelper3',
      route: undefined,
      endpoint: undefined,
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/home.helper.tsx',
        line: 54,
        column: 40,
      },
      import: async () => (await import('../pages/home.helper.js')).ExternalHelperComponent3,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'client',
          type: 'root',
          name: 'client',
          id: 'client.root.client',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 22,
          },
        },
      ],
      layouts: [],
    },
    {
      scope: 'client',
      type: 'provider',
      name: 'testClientCtx1',
      id: 'client.provider.testClientCtx1',
      route: undefined,
      endpoint: undefined,
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client-ctx.ts',
        line: 3,
        column: 26,
      },
      import: async () => (await import('./client-ctx.js')).clientCtx1,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'client',
          type: 'root',
          name: 'client',
          id: 'client.root.client',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 22,
          },
        },
      ],
      layouts: [],
    },
    {
      scope: 'client',
      type: 'provider',
      name: 'testClientCtx2',
      id: 'client.provider.testClientCtx2',
      route: undefined,
      endpoint: {
        method: 'POST',
        route: Route0.create('/_point0/client/provider/testClientCtx2'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client-ctx.ts',
        line: 11,
        column: 26,
      },
      import: async () => (await import('./client-ctx.js')).clientCtx2,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'client',
          type: 'root',
          name: 'client',
          id: 'client.root.client',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 22,
          },
        },
      ],
      layouts: [],
    },
    {
      scope: 'client',
      type: 'provider',
      name: 'testClientCtx3',
      id: 'client.provider.testClientCtx3',
      route: undefined,
      endpoint: {
        method: 'POST',
        route: Route0.create('/_point0/client/provider/testClientCtx3'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client-ctx.ts',
        line: 28,
        column: 26,
      },
      import: async () => (await import('./client-ctx.js')).clientCtx3,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'client',
          type: 'root',
          name: 'client',
          id: 'client.root.client',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 22,
          },
        },
      ],
      layouts: [],
    },
    {
      scope: 'client',
      type: 'mutation',
      name: 'clientFn2Mutation',
      id: 'client.mutation.clientFn2Mutation',
      route: undefined,
      endpoint: {
        method: 'POST',
        route: Route0.create('/_point0/client/mutation/clientFn2Mutation'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/idea-create.tsx',
        line: 125,
        column: 33,
      },
      import: async () => (await import('../pages/idea-create.js')).clientFn2Mutation,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'client',
          type: 'root',
          name: 'client',
          id: 'client.root.client',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 22,
          },
        },
      ],
      layouts: [],
    },
    {
      scope: 'client',
      type: 'mutation',
      name: 'clientFnMutation',
      id: 'client.mutation.clientFnMutation',
      route: undefined,
      endpoint: undefined,
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/idea-create.tsx',
        line: 107,
        column: 32,
      },
      import: async () => (await import('../pages/idea-create.js')).clientFnMutation,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'client',
          type: 'root',
          name: 'client',
          id: 'client.root.client',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 22,
          },
        },
      ],
      layouts: [],
    },
    {
      scope: 'client',
      type: 'mutation',
      name: 'clientFnMutation2',
      id: 'client.mutation.clientFnMutation2',
      route: undefined,
      endpoint: {
        method: 'POST',
        route: Route0.create('/_point0/client/mutation/clientFnMutation2'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/idea-create.tsx',
        line: 116,
        column: 33,
      },
      import: async () => (await import('../pages/idea-create.js')).clientFnMutationX,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'client',
          type: 'root',
          name: 'client',
          id: 'client.root.client',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 22,
          },
        },
      ],
      layouts: [],
    },
    {
      scope: 'client',
      type: 'mutation',
      name: 'createIdea',
      id: 'client.mutation.createIdea',
      route: undefined,
      endpoint: {
        method: 'POST',
        route: Route0.create('/_point0/client/mutation/createIdea'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/idea-create.tsx',
        line: 13,
        column: 34,
      },
      import: async () => (await import('../pages/idea-create.js')).createIdeaMutation,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'client',
          type: 'root',
          name: 'client',
          id: 'client.root.client',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 22,
          },
        },
      ],
      layouts: [],
    },
    {
      scope: 'client',
      type: 'mutation',
      name: 'generateIdea',
      id: 'client.mutation.generateIdea',
      route: undefined,
      endpoint: {
        method: 'POST',
        route: Route0.create('/_point0/client/mutation/generateIdea'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/idea-create.tsx',
        line: 82,
        column: 36,
      },
      import: async () => (await import('../pages/idea-create.js')).generateIdeaMutation,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'client',
          type: 'root',
          name: 'client',
          id: 'client.root.client',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 22,
          },
        },
      ],
      layouts: [],
    },
    {
      scope: 'client',
      type: 'mutation',
      name: 'generateIdea1',
      id: 'client.mutation.generateIdea1',
      route: undefined,
      endpoint: {
        method: 'POST',
        route: Route0.create('/_point0/client/mutation/generateIdea1'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/x/gi2.tsx',
        line: 6,
        column: 36,
      },
      import: async () => (await import('../pages/x/gi2.js')).generateIdeaMutation,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'client',
          type: 'root',
          name: 'client',
          id: 'client.root.client',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 22,
          },
        },
      ],
      layouts: [],
    },
    {
      scope: 'client',
      type: 'mutation',
      name: 'generateIdea2',
      id: 'client.mutation.generateIdea2',
      route: undefined,
      endpoint: {
        method: 'POST',
        route: Route0.create('/_point0/client/mutation/generateIdea2'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/x/gi2 copy.tsx',
        line: 6,
        column: 36,
      },
      import: async () => (await import('../pages/x/gi2 copy.js')).generateIdeaMutation,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'client',
          type: 'root',
          name: 'client',
          id: 'client.root.client',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 22,
          },
        },
      ],
      layouts: [],
    },
    {
      scope: 'client',
      type: 'mutation',
      name: 'uploadFile',
      id: 'client.mutation.uploadFile',
      route: undefined,
      endpoint: {
        method: 'POST',
        route: Route0.create('/_point0/client/mutation/uploadFile'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/file.tsx',
        line: 51,
        column: 34,
      },
      import: async () => (await import('../pages/file.js')).uploadFileMutation,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'client',
          type: 'root',
          name: 'client',
          id: 'client.root.client',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 22,
          },
        },
      ],
      layouts: [],
    },
  ],
}
