import { Route0 } from '@devp0nt/route0'
import { Engine } from '@point0/engine'
export default {
  engine: {
    file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/engine.ts',
    import: async () => (await Engine.findAndImportSelf({ engineFile: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/engine.ts' })).engine,
    server: {
      scope: 'root',
    },
    clients: [
      {
        scope: 'root',
      },
    ],
  },
  points: [
    {
      scope: 'root',
      type: 'root',
      name: 'root',
      id: 'root.root.root',
      route: undefined,
      endpoint: undefined,
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
        line: 5,
        column: 20,
      },
      import: async () => (await import('./client.js')).root,
      valid: true,
      errors: [],
      ssr: true,
      parents: [],
      layouts: [],
    },
    {
      scope: 'root',
      type: 'page',
      name: 'home',
      id: 'root.page.home',
      route: Route0.create('/'),
      endpoint: {
        method: 'GET',
        route: Route0.create('/_point0/root/page/home'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/home.tsx',
        line: 105,
        column: 15,
      },
      import: async () => (await import('../pages/home.js')).default,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'root',
          type: 'layout',
          name: 'generalLayout',
          id: 'root.layout.generalLayout',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/general.tsx',
            line: 7,
            column: 29,
          },
        },
        {
          scope: 'root',
          type: 'root',
          name: 'root',
          id: 'root.root.root',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 20,
          },
        },
      ],
      layouts: [
        {
          scope: 'root',
          type: 'layout',
          name: 'generalLayout',
          id: 'root.layout.generalLayout',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/general.tsx',
            line: 7,
            column: 29,
          },
        },
      ],
    },
    {
      scope: 'root',
      type: 'page',
      name: 'empty',
      id: 'root.page.empty',
      route: Route0.create('/empty/:x'),
      endpoint: {
        method: 'GET',
        route: Route0.create('/_point0/root/page/empty/empty/:x'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/empty.tsx',
        line: 20,
        column: 21,
      },
      import: async () => (await import('../pages/empty.js')).empty,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'root',
          type: 'root',
          name: 'root',
          id: 'root.root.root',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 20,
          },
        },
      ],
      layouts: [],
    },
    {
      scope: 'root',
      type: 'page',
      name: 'file',
      id: 'root.page.file',
      route: Route0.create('/file'),
      endpoint: {
        method: 'GET',
        route: Route0.create('/_point0/root/page/file/file'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/file.tsx',
        line: 6,
        column: 24,
      },
      import: async () => (await import('../pages/file.js')).filePage,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'root',
          type: 'root',
          name: 'root',
          id: 'root.root.root',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 20,
          },
        },
      ],
      layouts: [],
    },
    {
      scope: 'root',
      type: 'page',
      name: 'gi1',
      id: 'root.page.gi1',
      route: Route0.create('/gi1'),
      endpoint: {
        method: 'GET',
        route: Route0.create('/_point0/root/page/gi1/gi1'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/x/gi2.tsx',
        line: 27,
        column: 23,
      },
      import: async () => (await import('../pages/x/gi2.js')).gi1Page,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'root',
          type: 'layout',
          name: 'generalLayout',
          id: 'root.layout.generalLayout',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/general.tsx',
            line: 7,
            column: 29,
          },
        },
        {
          scope: 'root',
          type: 'root',
          name: 'root',
          id: 'root.root.root',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 20,
          },
        },
      ],
      layouts: [
        {
          scope: 'root',
          type: 'layout',
          name: 'generalLayout',
          id: 'root.layout.generalLayout',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/general.tsx',
            line: 7,
            column: 29,
          },
        },
      ],
    },
    {
      scope: 'root',
      type: 'page',
      name: 'gi2',
      id: 'root.page.gi2',
      route: Route0.create('/gi2'),
      endpoint: {
        method: 'GET',
        route: Route0.create('/_point0/root/page/gi2/gi2'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/x/gi2 copy.tsx',
        line: 27,
        column: 23,
      },
      import: async () => (await import('../pages/x/gi2 copy.js')).gi1Page,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'root',
          type: 'layout',
          name: 'generalLayout',
          id: 'root.layout.generalLayout',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/general.tsx',
            line: 7,
            column: 29,
          },
        },
        {
          scope: 'root',
          type: 'root',
          name: 'root',
          id: 'root.root.root',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 20,
          },
        },
      ],
      layouts: [
        {
          scope: 'root',
          type: 'layout',
          name: 'generalLayout',
          id: 'root.layout.generalLayout',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/general.tsx',
            line: 7,
            column: 29,
          },
        },
      ],
    },
    {
      scope: 'root',
      type: 'page',
      name: 'ideas',
      id: 'root.page.ideas',
      route: Route0.create('/ideas'),
      endpoint: {
        method: 'GET',
        route: Route0.create('/_point0/root/page/ideas/ideas'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/ideas.tsx',
        line: 6,
        column: 25,
      },
      import: async () => (await import('../pages/ideas.js')).ideasPage,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'root',
          type: 'layout',
          name: 'generalLayout',
          id: 'root.layout.generalLayout',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/general.tsx',
            line: 7,
            column: 29,
          },
        },
        {
          scope: 'root',
          type: 'root',
          name: 'root',
          id: 'root.root.root',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 20,
          },
        },
      ],
      layouts: [
        {
          scope: 'root',
          type: 'layout',
          name: 'generalLayout',
          id: 'root.layout.generalLayout',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/general.tsx',
            line: 7,
            column: 29,
          },
        },
      ],
    },
    {
      scope: 'root',
      type: 'page',
      name: 'newIdea',
      id: 'root.page.newIdea',
      route: Route0.create('/ideas/new'),
      endpoint: {
        method: 'GET',
        route: Route0.create('/_point0/root/page/newIdea/ideas/new'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/idea-create.tsx',
        line: 154,
        column: 30,
      },
      import: async () => (await import('../pages/idea-create.js')).ideaCreatePage,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'root',
          type: 'layout',
          name: 'generalLayout',
          id: 'root.layout.generalLayout',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/general.tsx',
            line: 7,
            column: 29,
          },
        },
        {
          scope: 'root',
          type: 'root',
          name: 'root',
          id: 'root.root.root',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 20,
          },
        },
      ],
      layouts: [
        {
          scope: 'root',
          type: 'layout',
          name: 'generalLayout',
          id: 'root.layout.generalLayout',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/general.tsx',
            line: 7,
            column: 29,
          },
        },
      ],
    },
    {
      scope: 'root',
      type: 'page',
      name: 'idea',
      id: 'root.page.idea',
      route: Route0.create('/ideas/:id'),
      endpoint: {
        method: 'GET',
        route: Route0.create('/_point0/root/page/idea/ideas/:id'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/idea.tsx',
        line: 15,
        column: 24,
      },
      import: async () => (await import('../pages/idea.js')).ideaPage,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'root',
          type: 'layout',
          name: 'idea',
          id: 'root.layout.idea',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/idea.tsx',
            line: 5,
            column: 26,
          },
        },
        {
          scope: 'root',
          type: 'layout',
          name: 'generalLayout',
          id: 'root.layout.generalLayout',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/general.tsx',
            line: 7,
            column: 29,
          },
        },
        {
          scope: 'root',
          type: 'root',
          name: 'root',
          id: 'root.root.root',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 20,
          },
        },
      ],
      layouts: [
        {
          scope: 'root',
          type: 'layout',
          name: 'generalLayout',
          id: 'root.layout.generalLayout',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/general.tsx',
            line: 7,
            column: 29,
          },
        },
        {
          scope: 'root',
          type: 'layout',
          name: 'idea',
          id: 'root.layout.idea',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/idea.tsx',
            line: 5,
            column: 26,
          },
        },
      ],
    },
    {
      scope: 'root',
      type: 'page',
      name: 'ideaNews',
      id: 'root.page.ideaNews',
      route: Route0.create('/ideas/:id/news'),
      endpoint: {
        method: 'GET',
        route: Route0.create('/_point0/root/page/ideaNews/ideas/:id/news'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/idea-news.tsx',
        line: 5,
        column: 28,
      },
      import: async () => (await import('../pages/idea-news.js')).ideaNewsPage,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'root',
          type: 'layout',
          name: 'idea',
          id: 'root.layout.idea',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/idea.tsx',
            line: 5,
            column: 26,
          },
        },
        {
          scope: 'root',
          type: 'layout',
          name: 'generalLayout',
          id: 'root.layout.generalLayout',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/general.tsx',
            line: 7,
            column: 29,
          },
        },
        {
          scope: 'root',
          type: 'root',
          name: 'root',
          id: 'root.root.root',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 20,
          },
        },
      ],
      layouts: [
        {
          scope: 'root',
          type: 'layout',
          name: 'generalLayout',
          id: 'root.layout.generalLayout',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/general.tsx',
            line: 7,
            column: 29,
          },
        },
        {
          scope: 'root',
          type: 'layout',
          name: 'idea',
          id: 'root.layout.idea',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/idea.tsx',
            line: 5,
            column: 26,
          },
        },
      ],
    },
    {
      scope: 'root',
      type: 'page',
      name: 'md2',
      id: 'root.page.md2',
      route: Route0.create('/md2'),
      endpoint: {
        method: 'GET',
        route: Route0.create('/_point0/root/page/md2/md2'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/md2.mdx',
        line: 5,
        column: 20,
      },
      import: async () => (await import('../pages/md2.mdx')).page,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'root',
          type: 'root',
          name: 'root',
          id: 'root.root.root',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 20,
          },
        },
      ],
      layouts: [],
    },
    {
      scope: 'root',
      type: 'page',
      name: 'sharedEmpty',
      id: 'root.page.sharedEmpty',
      route: Route0.create('/sharedEmpty2'),
      endpoint: {
        method: 'GET',
        route: Route0.create('/_point0/root/page/sharedEmpty/sharedEmpty2'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/empty.tsx',
        line: 55,
        column: 31,
      },
      import: async () => (await import('../pages/empty.js')).sharedEmptyPage,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'root',
          type: 'root',
          name: 'root',
          id: 'root.root.root',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 20,
          },
        },
      ],
      layouts: [],
    },
    {
      scope: 'root',
      type: 'layout',
      name: 'generalLayout',
      id: 'root.layout.generalLayout',
      route: Route0.create('/'),
      endpoint: undefined,
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/general.tsx',
        line: 7,
        column: 29,
      },
      import: async () => (await import('../layouts/general.js')).generalLayout,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'root',
          type: 'root',
          name: 'root',
          id: 'root.root.root',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 20,
          },
        },
      ],
      layouts: [],
    },
    {
      scope: 'root',
      type: 'layout',
      name: 'idea',
      id: 'root.layout.idea',
      route: Route0.create('/ideas/:id'),
      endpoint: {
        method: 'GET',
        route: Route0.create('/_point0/root/layout/idea/ideas/:id'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/idea.tsx',
        line: 5,
        column: 26,
      },
      import: async () => (await import('../layouts/idea.js')).ideaLayout,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'root',
          type: 'layout',
          name: 'generalLayout',
          id: 'root.layout.generalLayout',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/general.tsx',
            line: 7,
            column: 29,
          },
        },
        {
          scope: 'root',
          type: 'root',
          name: 'root',
          id: 'root.root.root',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 20,
          },
        },
      ],
      layouts: [
        {
          scope: 'root',
          type: 'layout',
          name: 'generalLayout',
          id: 'root.layout.generalLayout',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/layouts/general.tsx',
            line: 7,
            column: 29,
          },
        },
      ],
    },
    {
      scope: 'root',
      type: 'component',
      name: 'BestIdea',
      id: 'root.component.BestIdea',
      route: undefined,
      endpoint: {
        method: 'POST',
        route: Route0.create('/_point0/root/component/BestIdea'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/home.tsx',
        line: 36,
        column: 33,
      },
      import: async () => (await import('../pages/home.js')).BestIdeaComponent,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'root',
          type: 'root',
          name: 'root',
          id: 'root.root.root',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 20,
          },
        },
      ],
      layouts: [],
    },
    {
      scope: 'root',
      type: 'component',
      name: 'externalHelper2',
      id: 'root.component.externalHelper2',
      route: undefined,
      endpoint: undefined,
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/home.helper.tsx',
        line: 30,
        column: 40,
      },
      import: async () => (await import('../pages/home.helper.js')).externalHelper2Component,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'root',
          type: 'root',
          name: 'root',
          id: 'root.root.root',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 20,
          },
        },
      ],
      layouts: [],
    },
    {
      scope: 'root',
      type: 'component',
      name: 'externalHelper3',
      id: 'root.component.externalHelper3',
      route: undefined,
      endpoint: undefined,
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/home.helper.tsx',
        line: 54,
        column: 40,
      },
      import: async () => (await import('../pages/home.helper.js')).externalHelper3Component,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'root',
          type: 'root',
          name: 'root',
          id: 'root.root.root',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 20,
          },
        },
      ],
      layouts: [],
    },
    {
      scope: 'root',
      type: 'provider',
      name: 'testClientCtx1',
      id: 'root.provider.testClientCtx1',
      route: undefined,
      endpoint: undefined,
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client-ctx.ts',
        line: 3,
        column: 26,
      },
      import: async () => (await import('./client-ctx.js')).clientCtx1,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'root',
          type: 'root',
          name: 'root',
          id: 'root.root.root',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 20,
          },
        },
      ],
      layouts: [],
    },
    {
      scope: 'root',
      type: 'provider',
      name: 'testClientCtx2',
      id: 'root.provider.testClientCtx2',
      route: undefined,
      endpoint: {
        method: 'POST',
        route: Route0.create('/_point0/root/provider/testClientCtx2'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client-ctx.ts',
        line: 11,
        column: 26,
      },
      import: async () => (await import('./client-ctx.js')).clientCtx2,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'root',
          type: 'root',
          name: 'root',
          id: 'root.root.root',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 20,
          },
        },
      ],
      layouts: [],
    },
    {
      scope: 'root',
      type: 'provider',
      name: 'testClientCtx3',
      id: 'root.provider.testClientCtx3',
      route: undefined,
      endpoint: {
        method: 'POST',
        route: Route0.create('/_point0/root/provider/testClientCtx3'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client-ctx.ts',
        line: 28,
        column: 26,
      },
      import: async () => (await import('./client-ctx.js')).clientCtx3,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'root',
          type: 'root',
          name: 'root',
          id: 'root.root.root',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 20,
          },
        },
      ],
      layouts: [],
    },
    {
      scope: 'root',
      type: 'mutation',
      name: 'clientFn2Mutation',
      id: 'root.mutation.clientFn2Mutation',
      route: undefined,
      endpoint: {
        method: 'POST',
        route: Route0.create('/_point0/root/mutation/clientFn2Mutation'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/idea-create.tsx',
        line: 100,
        column: 33,
      },
      import: async () => (await import('../pages/idea-create.js')).clientFn2Mutation,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'root',
          type: 'root',
          name: 'root',
          id: 'root.root.root',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 20,
          },
        },
      ],
      layouts: [],
    },
    {
      scope: 'root',
      type: 'mutation',
      name: 'clientFnMutation',
      id: 'root.mutation.clientFnMutation',
      route: undefined,
      endpoint: undefined,
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/idea-create.tsx',
        line: 82,
        column: 32,
      },
      import: async () => (await import('../pages/idea-create.js')).clientFnMutation,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'root',
          type: 'root',
          name: 'root',
          id: 'root.root.root',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 20,
          },
        },
      ],
      layouts: [],
    },
    {
      scope: 'root',
      type: 'mutation',
      name: 'clientFnMutation2',
      id: 'root.mutation.clientFnMutation2',
      route: undefined,
      endpoint: {
        method: 'POST',
        route: Route0.create('/_point0/root/mutation/clientFnMutation2'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/idea-create.tsx',
        line: 91,
        column: 33,
      },
      import: async () => (await import('../pages/idea-create.js')).clientFnMutationX,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'root',
          type: 'root',
          name: 'root',
          id: 'root.root.root',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 20,
          },
        },
      ],
      layouts: [],
    },
    {
      scope: 'root',
      type: 'mutation',
      name: 'createIdea',
      id: 'root.mutation.createIdea',
      route: undefined,
      endpoint: {
        method: 'POST',
        route: Route0.create('/_point0/root/mutation/createIdea'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/idea-create.tsx',
        line: 13,
        column: 34,
      },
      import: async () => (await import('../pages/idea-create.js')).createIdeaMutation,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'root',
          type: 'root',
          name: 'root',
          id: 'root.root.root',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 20,
          },
        },
      ],
      layouts: [],
    },
    {
      scope: 'root',
      type: 'mutation',
      name: 'generateIdea',
      id: 'root.mutation.generateIdea',
      route: undefined,
      endpoint: {
        method: 'POST',
        route: Route0.create('/_point0/root/mutation/generateIdea'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/idea-create.tsx',
        line: 129,
        column: 36,
      },
      import: async () => (await import('../pages/idea-create.js')).generateIdeaMutation,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'root',
          type: 'root',
          name: 'root',
          id: 'root.root.root',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 20,
          },
        },
      ],
      layouts: [],
    },
    {
      scope: 'root',
      type: 'mutation',
      name: 'generateIdea1',
      id: 'root.mutation.generateIdea1',
      route: undefined,
      endpoint: {
        method: 'POST',
        route: Route0.create('/_point0/root/mutation/generateIdea1'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/x/gi2.tsx',
        line: 6,
        column: 36,
      },
      import: async () => (await import('../pages/x/gi2.js')).generateIdeaMutation,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'root',
          type: 'root',
          name: 'root',
          id: 'root.root.root',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 20,
          },
        },
      ],
      layouts: [],
    },
    {
      scope: 'root',
      type: 'mutation',
      name: 'generateIdea2',
      id: 'root.mutation.generateIdea2',
      route: undefined,
      endpoint: {
        method: 'POST',
        route: Route0.create('/_point0/root/mutation/generateIdea2'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/x/gi2 copy.tsx',
        line: 6,
        column: 36,
      },
      import: async () => (await import('../pages/x/gi2 copy.js')).generateIdeaMutation,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'root',
          type: 'root',
          name: 'root',
          id: 'root.root.root',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 20,
          },
        },
      ],
      layouts: [],
    },
    {
      scope: 'root',
      type: 'mutation',
      name: 'uploadFile',
      id: 'root.mutation.uploadFile',
      route: undefined,
      endpoint: {
        method: 'POST',
        route: Route0.create('/_point0/root/mutation/uploadFile'),
      },
      pos: {
        file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/pages/file.tsx',
        line: 51,
        column: 34,
      },
      import: async () => (await import('../pages/file.js')).uploadFileMutation,
      valid: true,
      errors: [],
      ssr: true,
      parents: [
        {
          scope: 'root',
          type: 'root',
          name: 'root',
          id: 'root.root.root',
          pos: {
            file: '/Users/iserdmi/cc/opensource/devp0nt/point0/examples/basic/src/lib/client.tsx',
            line: 5,
            column: 20,
          },
        },
      ],
      layouts: [],
    },
  ],
}
