import type { PointsDefinition } from '@point0/core'
import { client as root_0 } from './client.js'
export default [
  root_0,
  {
    type: 'page',
    name: 'home',
    route: '/',
    polh: true,
    layouts: ['generalLayout'],
    point: async () => (await import('../pages/home.js')).default,
  },
  {
    type: 'page',
    name: 'empty',
    route: '/empty/:x',
    polh: true,
    point: async () => (await import('../pages/empty.js')).empty,
  },
  {
    type: 'page',
    name: 'file',
    route: '/file',
    polh: true,
    point: async () => (await import('../pages/file.js')).filePage,
  },
  {
    type: 'page',
    name: 'gi1',
    route: '/gi1',
    polh: true,
    layouts: ['generalLayout'],
    point: async () => (await import('../pages/x/gi2.js')).gi1Page,
  },
  {
    type: 'page',
    name: 'gi2',
    route: '/gi2',
    polh: true,
    layouts: ['generalLayout'],
    point: async () => (await import('../pages/x/gi2 copy.js')).gi1Page,
  },
  {
    type: 'page',
    name: 'ideas',
    route: '/ideas',
    polh: true,
    layouts: ['generalLayout'],
    point: async () => (await import('../pages/ideas.js')).ideasPage,
  },
  {
    type: 'page',
    name: 'newIdea',
    route: '/ideas/new',
    polh: true,
    layouts: ['generalLayout'],
    point: async () => (await import('../pages/idea-create.js')).ideaCreatePage,
  },
  {
    type: 'page',
    name: 'idea',
    route: '/ideas/:id',
    polh: true,
    layouts: ['generalLayout', 'idea'],
    point: async () => (await import('../pages/idea.js')).ideaPage,
  },
  {
    type: 'page',
    name: 'ideaNews',
    route: '/ideas/:id/news',
    polh: 2000,
    layouts: ['generalLayout', 'idea'],
    point: async () => (await import('../pages/idea-news.js')).ideaNewsPage,
  },
  {
    type: 'page',
    name: 'md2',
    route: '/md2',
    polh: true,
    point: async () => (await import('../pages/md2.mdx')).page,
  },
  {
    type: 'page',
    name: 'sharedEmpty',
    route: '/sharedEmpty2',
    polh: true,
    point: async () => (await import('../pages/empty.js')).sharedEmptyPage,
  },
  {
    type: 'layout',
    name: 'generalLayout',
    route: '/',
    point: async () => (await import('../layouts/general.js')).generalLayout,
  },
  {
    type: 'layout',
    name: 'idea',
    route: '/ideas/:id',
    point: async () => (await import('../layouts/idea.js')).ideaLayout,
  },
] as PointsDefinition<typeof root_0['Infer']['RequiredCtx'], typeof root_0['Infer']['Error']>
